name: word-list-generator

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        
      - name: Create Environment
        run: make create-environment

      - name: Install dependencies
        run: make dev-setup

      - name: Run checks
        run: make run-checks